### ISSUE TITLE
Explicit event retention policy in event stream metadata

### ISSUE THREAD

**Issue by ysarig1** [openid/sharedsignals#107]
Related to: https://github.com/openid/sharedsignals/issues/106.
The SSF spec include two cases where events may be queued in an event stream:
1.	When an event stream is paused (see section 7.1.2)
2.	When a poll delivery method is used (see section 7.1.1)

In both cases, there is a possibility of many events queueing by the transmitter to the point that it is not practical for the transmitter to retain. We should consider adding an explicit limit to the number of events (or time?) that can be retained by the transmitter to event stream metadata.

**Comment by tulshi** [comment]
Does the new language in section 7.1.2 address this issue?

**Comment by ysarig1** [comment]
@tulshi I don't see any recent relevant update in 7.1.2 that addresses the event retention issue (as @independentid pointed out). This is something that need to be addressed before 1_0-ID2.

**Comment by tulshi** [comment]
Ok. I see the problem. The status values are repeated in 7.1.2.1, whereas they were cleaned up in 7.1.2. I will remove the ambiguity and problematice language from 7.1.2.1, since they are already specified in 7.1.2

**Comment by tulshi** [comment]
@ysarig1 is this issue closed in the latest spec? If so, could you please close this? Thanks

**Comment by timcappalli** [comment]
Closed due to inactivity.
