### ISSUE TITLE
Why are iss and aud not present when creating a stream (Sec 7.1.1.1)?

### ISSUE THREAD

**Issue by independentid** [openid/sharedsignals#110]
An SSF server may have events from multiple publishers and support multiple receivers.

In particular, without an Aud parameter how does the server know who it is sending to?  If not supplied, how is Aud calculated for the response?

My use cases require iss and aud parameters in addition to events requested.

**Comment by FragLegs** [comment]
This is a good call out. It used to be that the Transmitter knew the Aud based on the bearer token. But I think the recent changes we've been discussing about decoupling SSF from OAuth means that we should make Aud a **Receiver-supplied** value.

**Comment by independentid** [comment]
An SSF server may have multiple event sources behind it.  By not having iss configurable, the SSF server would have to re-publish (ie sign) each event.  This would also make it harder (as in non-standard) for the receiver to select which sources it wants.

**Comment by appsdesh** [comment]
As we decouple OAuth from SSF, we will need receiver to indicate what the `aud` claim should be in the SETs. Making this as a must have field in the stream create request. It also makes sense to add it in the update request

**Comment by tulshi** [comment]
Issue #30 is related to this.
