### ISSUE TITLE
7.1.2.2 Update Stream Status (inconsistent use of HTTP POST for modify vs. create)

### ISSUE THREAD

**Issue by independentid** [openid/sharedsignals#113]
In stream management, HTTP POST is used to create a new stream and PUT/PATCH is used to update.

Yet in stream status, POST is used to update.

Recommend for consistency supporting PUT to update the stream status.  The use of POST could be deprecated to preserve backward compatibility.

This is not a big deal. But it is an inconsistency with matching CRUD operations to HTTP POST, GET, PUT, DELETE.

**Comment by tulshi** [comment]
Since this is going to be a breaking change, I'd like to say we won't be fixing this one, and closing this issue. If anyone feels we should still do this, please reopen this issue.
