### ISSUE TITLE
add_subject_endpoint and remove_subject_endpoint endpoints

### ISSUE THREAD

**Issue by adeinega** [openid/sharedsignals#13]
I'm curious if there is any particular reason to use the POST method in order to remove a subject from an event stream? Wouldn't it be a better choice to just use the DELETE method?

In addition to that, the specification currently uses

```
  "add_subject_endpoint":
    "https://tr.example.com/sse/mgmt/subject:add",
  "remove_subject_endpoint":
    "https://tr.example.com/sse/mgmt/subject:remove"
```

":" in both endpoints should be encoded as "%3A", this way
https://tr.example.com/sse/mgmt/subject:add becomes https://tr.example.com/sse/mgmt/subject%3Aadd, and
https://tr.example.com/sse/mgmt/subject:remove becomes https://tr.example.com/sse/mgmt/subject%3Aremove

The same applies to other examples.

**Comment by tulshi** [comment]
Since this will be a breaking change, I'd like to close this issue. Please re-open if you think this needs to be worked on.
