### ISSUE TITLE
The examples for stream update requests should not include Transmitter-Supplied fields in the request

### ISSUE THREAD

**Issue by ysarig1** [openid/sharedsignals#150]
The current examples for stream update requests (both PUT and PATCH) include fields that are Transmitter-Supplied ("iss" for PATCH, "iss" and "aud" for PUT) and they should be removed from the examples.

**Comment by FragLegs** [comment]
Transmitter-Supplied properties are perfectly acceptable in both PUT and PATCH. The only restriction is that if they do not match the Transmitter's expectation for those values, the Transmitter should return an error. In fact, the `stream_id`, which is Transmitter-Supplied, MUST be present in the request.

**Comment by ysarig1** [comment]
Including those values in the examples is confusing, especially in the PATCH case. While they may be accepted in the request, there is no reason for them to be there in PATCH case.

**Comment by FragLegs** [comment]
This is being worked on in #152
