### ISSUE TITLE
Clarify that only one event is allowed per SET

### ISSUE THREAD

**Issue by FragLegs** [openid/sharedsignals#167]
During the 5/14/24 WG meeting we discussed the need to clarify that only one event (key/value pair in the `events` claim) is allowed per SET.

**Comment by timcappalli** [comment]
Since we're now requiring the subject to be at the top level of the SET, should we consider allowing multiple events around the same subject? The request has come up in the past.

**Comment by jischr** [comment]
i see a lot of advantages to allowing multiple events in larger scale implementations, running bulk jobs, etc.

@atultulshi what are your thoughts on this?

**Comment by tulshi** [comment]
I agree there are benefits to be able to send multiple events. Whether we want to do this before 1.0 is a question I'm trying to grapple with. My (weakly held) opinion is that we should move this to be after the 1.0 spec.

**Comment by independentid** [comment]
The stipulation in SET rfc is multiple events are possible as long as it is just different statements about the same transaction.  Eg you could gave both a scim state change event and a risc signals event from the same transaction. The trade off of splitting into single event payloads, receivers may assume two or more events are multiple transactions unless they check the txn value. Multiple different transactions in a set are not allowed.  Multiple payloads are. PhilOn May 16, 2024, at 8:11 AM, Jen Schreiber ***@***.***> wrote:﻿
i see a lot of advantages to allowing multiple events in larger scale implementations, running bulk jobs, etc.
@atultulshi what are your thoughts on this?

**Comment by FragLegs** [comment]
Closed by https://github.com/openid/sharedsignals/pull/179
