### ISSUE TITLE
Receiver expectations for Transmitter's "default_subjects" advertised in well-known discovery endpoint

### ISSUE THREAD

**Issue by xtrycatchx** [openid/sharedsignals#192]
Is it safe to assume these?

| Transmitter discovery  | Receiver behaviour |
| -----------------------   | ------- |
| `default_subjects: ALL` | by default will [receive all events](https://openid.net/specs/openid-caep-interoperability-profile-1_0-00.html#name-implicitly-added-subjects) without the need to invoke [addsubject-endpoint](https://openid.net/specs/openid-sharedsignals-framework-1_0-03.html#section-6.1-18) |
| `default_subjects: NONE`| will not receive events. need to invoke [addsubject-endpoint](https://openid.net/specs/openid-sharedsignals-framework-1_0-03.html#section-6.1-18)  for subject of interest   |
| no `default_subject` from discovery metadata | the same behaviour as  `default_subjects: NONE`   |

tnx

**Comment by FragLegs** [comment]
The first two rows are correct. However, if there is no `default_subject` in the metadata, then the behavior is undefined and you should contact the owner of the Transmitter to determine the expected behavior.

**Comment by xtrycatchx** [comment]
closing this as the inquiry has been answered
