### ISSUE TITLE
Update Makefile to automatically build targets

### ISSUE THREAD

**Issue by tulshi** [openid/sharedsignals#26]
SSE and RISC use XML as source, CAEP uses MD as source. We need a Makefile that builds the TXT and HTML outputs from these sources.

**Comment by adeinega** [comment]
It would be really great & convenient to have MD everywhere. Take a look at the same https://github.com/openid/sse/pull/9#issuecomment-1209830781.

**Comment by FragLegs** [comment]
I love @adeinega 's idea. Instead of maintaining 3 copies of each document, let's only keep Markdown in this repo and auto-generate the others as needed for publishing.
