### ISSUE TITLE
Should POLL URL be specified in the "delivery methods supported"?

### ISSUE THREAD

**Issue by FragLegs** [openid/sharedsignals#36]
From @atultulshi in a comment on #9 

> In the Transmitter Configuration Metadata, should we modify the "delivery methods supported" to include the POLL URL if the method is POLL?

**Comment by FragLegs** [comment]
The poll URI _MUST_ be unique per-stream, otherwise it is unclear which stream the Receiver is polling. So it would be hard to add it to the Transmitter Configuration Metadata. I'm not sure what advantage is gained by adding it there, since the Receiver already has access to it in the Stream Configuration data.

**Comment by tulshi** [comment]
In the current spec, the "delivery" field of the stream configuration is specified to be "Receiver supplied". This is OK for the push method, but for the poll method, the URL needs to be specified by the Transmitter, not the Receiver. Also, the text of the spec talks about a special field "method", but the examples give the field "delivery_method". We should clarify this in the updated spec.

**Comment by FragLegs** [comment]
Hmm, that one is tricky. The Receiver _is_ responsible for setting the `method` field of the `delivery` object, but if the Receiver selects "poll" then the Transmitter has to fill in the `url` field. So it is mostly Receiver supplied, but you are right that we should call out the Transmitter's responsibility when the Receiver chooses "poll".

**Comment by tulshi** [comment]
Labeled this as a bug, because implementers cannot discover the POLL URL of a Transmitter in the current spec.
