### ISSUE TITLE
Rework the "examples" sections

### ISSUE THREAD

**Issue by FragLegs** [openid/sharedsignals#37]
Some of our endpoints don't have examples. Others do. At least one of them (just below `Table 6: Read Stream Status Errors`) has a few examples that are general to all endpoints. Let's rework how we do examples. Maybe provide an examples section for the general ones and then make sure every endpoint has endpoint-specific examples and link to them from the examples section?

**Comment by timcappalli** [comment]
call on 2023-03-21: We need an inventory of the sections that lack examples. Peter and Tim to compile list.

**Comment by ptravers** [comment]
@FragLegs @timcappalli what is the threshold for requiring an example? from rereading the description we may want to agree to how exhaustive we want the examples to be

so far sections without examples in `openid-sharedsignals-framework-1_0.txt`:
6.1
7.1.5

**Comment by tulshi** [comment]
@timcappalli please provide an update as it looks like you had an action item related to this.

**Comment by FragLegs** [comment]
We also need to remove `subject` from the events payloads in the examples.

**Comment by FragLegs** [comment]
Figure 46 needs a sub_id

**Comment by FragLegs** [comment]
The following examples either need `subject` removed from the event, `sub_id` added to the base SET, or both:
- subject-ids-ex-simple
- subject-ids-ex-complex
- subject-properties-ex
- subject-custom-type-ex
- risc-event-subject-example
- caep-event-properties-example
- figarrayaud
