### ISSUE TITLE
Do we need separate endpoints for adding and removing a subject?

### ISSUE THREAD

**Issue by FragLegs** [openid/sharedsignals#39]
Right now, the transmitter configuration returned from `/.well-known` provides both an `add-subject-endpoint` and a `remove-subject-endpoint`. Can we just make that a `subject-endpoint` with POST and DELETE functionality?

**Comment by frankt-vmware** [comment]
See [comment](https://github.com/openid/sse/issues/4#issuecomment-1331129722) on main thread.

**Comment by FragLegs** [comment]
I would like to be able to consider this independently of the conversation about making the endpoints more REST-like (i.e. putting identifiers in the path, like `/ssf/stream/1234/subject/5678`). We can talk about that too, but should do it in a separate issue because it is a much larger scope of change.

**Comment by timcappalli** [comment]
call on 2023-03-21: wait until next call for discussion with @FragLegs

**Comment by FragLegs** [comment]
Just realized that this is a duplicate of #13

**Comment by tulshi** [comment]
closed because its a duplicate of #13
