### ISSUE TITLE
Create Stream description lacks option for "Stream already exists"

### ISSUE THREAD

**Issue by tulshi** [openid/sharedsignals#46]
If a Transmitter wanted to support only one stream between itself and a specific Receiver, then the Transmitter should have a way to respond to a Receiver that has already created a stream with a status 303 (see other) or some such way of indicating that a stream already exists.

**Comment by ptravers** [comment]
I would suggest returning 200 with the previously created entity. then return 201 if the stream did not already exist when create is called

**Comment by timcappalli** [comment]
There is precedent for @ptravers recommendation in the [SCIM core protocol](https://www.rfc-editor.org/rfc/rfc7644.html#section-3.4.1)

>  If the resource exists, the server responds with HTTP status code 200 (OK) and includes the result in the body of the response.

on 2023-03-21 call, consensus to follow this approach.
