### ISSUE TITLE
jwt-id should be jwt_id

### ISSUE THREAD

**Issue by FragLegs** [openid/sharedsignals#62]
Currently the spec uses [jwt-id](https://github.com/openid/sharedsignals/blob/main/openid-sharedsignals-framework-1_0.txt#L306) to describe the `JWT ID` simple subject format. This is at odds with all of the other simple subject formats that use underscores, like `saml_assertion_id`, `iss_sub` and `phone_number`.

And, in [one of the CAEP examples](https://github.com/openid/sharedsignals/blob/main/openid-caep-specification-1_0.txt#L366) we use the underscore as would be expected. We should update the SSF spec to use `jwt_id`.

**Comment by tulshi** [comment]
closed via pull req 63
