### ISSUE TITLE
If a transmitter supports CAEP events, should the delivery method be CAEP specific?

### ISSUE THREAD

**Issue by appsdesh** [openid/sharedsignals#65]
I noticed that delivery methods are limited to 

- https://schemas.openid.net/secevent/risc/delivery-method/poll
- https://schemas.openid.net/secevent/risc/delivery-method/push

If a transmitter only supports CAEP events, do you suggest it uses `risc` specific `delivery-method`s, or is ok to support the following?

- https://schemas.openid.net/secevent/caep/delivery-method/poll
- https://schemas.openid.net/secevent/caep/delivery-method/push

Both [[DELIVERYPOLL]](https://www.rfc-editor.org/info/rfc8936) and [[DELIVERYPUSH]](https://www.rfc-editor.org/info/rfc8935) don't provide guidance.

**Comment by independentid** [comment]
You may be confusing event types (expressed as SETs) with the transfer method protocols (SET Push and Poll Transfer).  AFAIK there is no protocol specific to caep. RFC8935 (SET Push),8936 (SET Poll) are standard transfer mechanisms for any SET. SSF just defines stream configuration management (eg what are the endpoints that 8935/8936 use) and the event types that will be transmitted. Thus limiting the event types to CAEP doesn’t affect the delivery method. PhilOn May 31, 2023, at 5:04 PM, Apoorva Deshpande ***@***.***> wrote:﻿
I noticed that delivery methods are limited to

https://schemas.openid.net/secevent/risc/delivery-method/poll
https://schemas.openid.net/secevent/risc/delivery-method/push

If a transmitter only supports CAEP events, do you suggest it uses risc specific delivery-methods, or is ok to support the following?

https://schemas.openid.net/secevent/caep/delivery-method/poll
https://schemas.openid.net/secevent/caep/delivery-method/push

**Comment by appsdesh** [comment]
Thanks, my question was more on the namespaces used in RFC8935 (SET Push),8936 (SET Poll) `delivery-method` semantics. It refers to `risc`. 
- https://schemas.openid.net/secevent/**risc**/delivery-method/poll
- https://schemas.openid.net/secevent/**risc**/delivery-method/push

But from your explanation, it appears that the transfer mechanisms namespace is standard and it would not reflect which profiles (risc/caep) are used in the transfer.

**Comment by independentid** [comment]
Great!PhilOn Jun 1, 2023, at 5:22 AM, FragLegs ***@***.***> wrote:﻿
@appsdesh I agree that it is confusing. We already have a PR up to fix it. It is approved and just waiting on @timcappalli to merge it. #49

**Comment by apoorvadeshpande-okta** [comment]
Thank you @FragLegs @independentid 👍🏽

**Comment by appsdesh** [comment]
Thank you @FragLegs @independentid 👍
