### ISSUE TITLE
Registration of well-known endpoint to IANA

### ISSUE THREAD

**Issue by appsdesh** [openid/sharedsignals#66]
From [rfc8651](https://www.rfc-editor.org/rfc/rfc8615) 
> Applications that wish to mint new well-known URIs MUST register them, following the procedures in [Section 5.1](https://www.rfc-editor.org/rfc/rfc8615#section-5.1), subject to the following requirements.

Already registered well-known URIs https://www.iana.org/assignments/well-known-uris/well-known-uris.xhtml

**Comment by FragLegs** [comment]
Done. See the [updated list here](https://www.iana.org/assignments/well-known-uris/well-known-uris.xhtml). Our well-known is currently listed as provisional. It will be updated to permanent once we release v1 of the spec (and sent the list maintainer a request to modify it).
