### ISSUE TITLE
Remove stream configuration API to respond back with with HTTP 204 - No Content instead of HTTP 200

### ISSUE THREAD

**Issue by appsdesh** [openid/sharedsignals#67]
As explained in [RFC9110](https://www.rfc-editor.org/rfc/rfc9110.html#name-delete) delete call to respond back with HTTP 204 if the action is successful and no further information is to be supplied.

Current SSF specification says the response should be HTTP 200 with the empty response body. The correct response code should be HTTP 204

[Remove subject](https://openid.net/specs/openid-sse-framework-1_0-ID1.html#removing-a-subject) correctly calls out 204 as a response code

**Comment by tulshi** [comment]
Has this been fixed in the draft spec? The line here says "204 OK": https://github.com/openid/sharedsignals/blob/ae0cf793477bff3953001b1f4ef04da78b9325e1/openid-sharedsignals-framework-1_0.txt#L1655

**Comment by appsdesh** [comment]
Thanks for pointing this out. 

Should we also clarify that "204" is "No Content" instead of an "OK"

**Comment by FragLegs** [comment]
Thanks for catching that @appsdesh . I have fixed it here in the world's tiniest pull request: #73
