### ISSUE TITLE
Authorization server metadata uses `scopes_supported` key vs SSF using `supported_scopes`

### ISSUE THREAD

**Issue by appsdesh** [openid/sharedsignals#95]
In order to bring consistency and reduce confusion should we align with [RFC8414](https://datatracker.ietf.org/doc/html/rfc8414) to use `supported_scopes` as key in the SSF config metadata?

**Comment by tulshi** [comment]
Actually I thought we deliberately made this different because the intent of those two fields is different. It should be in the meeting notes.

**Comment by appsdesh** [comment]
> Actually I thought we deliberately made this different because the intent of those two fields is different. It should be in the meeting notes.

@atultulshi 

The original [meeting notes from 6/27](https://hackmd.io/@oidf-wg-sse/wg-meeting-20230627) refer the field as `scopes_supported`

In the [following meeting of 7/11](https://hackmd.io/@oidf-wg-sse/wg-meeting-20230711) we restructured the JSON, and made it `supported_scope`. There are no references of consciously changing the naming to avoid conflict, so I assume this is just an oversight.

I agree that it could be confusing, so suggest using completely different naming rather than just flipping 2 words.

Some suggestions -
1. `scopes_required`
2. `scopes_mandatory`

**Comment by tulshi** [comment]
I don't think the intent of the fields is that those scopes are required or mandatory though. They describe scopes that are supported by the AS.

**Comment by appsdesh** [comment]
> I don't think the intent of the fields is that those scopes are required or mandatory though. They describe scopes that are supported by the AS.

The field itself is `OPTIONAL` but if it has scopes populated then it would be mandatory to request the token

**Comment by appsdesh** [comment]
@atultulshi I came across [OAuth 2.0 Protected Resource Metadata](https://datatracker.ietf.org/doc/html/draft-jones-oauth-resource-metadata-04) and it would make more sense to not stuff OAuth properties in the SSF metadata.

This spec suggests having a separate per protected resource metadata for the OAuth server.

**Comment by mcguinness** [comment]
I don't think `OpenID Shared Signals Framework Specification` configuration discovery metadata should directly include OAuth Resource Server metadata like scopes or authorization servers.  There is no requirement that SSF endpoints are OAuth 2.0 Protected Resources.

I see this working similar to SCIM where SSF metadata publishes supported `authenticationSchemes` like https://datatracker.ietf.org/doc/html/rfc7643#section-5

```
"authenticationSchemes": [
   {
     "name": "OAuth Bearer Token",
     "description":
       "Authentication scheme using the OAuth Bearer Token Standard",
     "specUri": "http://www.rfc-editor.org/info/rfc6750",
     "documentationUri": "http://example.com/help/oauth.html",
     "type": "oauthbearertoken",
     "primary": true
   }
]
```

When a SSF transmitter indicates support for OAuth 2.0 a client can then use OAuth based discovery calls according to those specifications.  

1. Get SSF Configuration Metadata

```
GET /.well-known/ssf-configuration HTTP/1.1
Host: tr.example.com
```

2. Discover OAuth as supported authentication scheme. Perform OAuth Protected Resource discovery for a published SSF management endpoint

```
GET /ssf/mgmt/stream/.well-known/oauth-protected-resource HTTP/1.1
Host: tr.example.com
```

3. Discover the Authorization Server, scopes, etc needed for the endpoint.  Perform OAuth Authorization Server discovery for the Authorization Server

```
GET /.well-known/oauth-authorization-server HTTP/1.1
Host: tr.example.com
```

4. Client now as all the data needed to obtain an `access_token` for a SSF management endpoint

This keeps SSF decoupled from OAuth and allows the relevant OAuth specs to address discovery use cases for OAuth client scenarios

**Comment by tulshi** [comment]
I agree with Karl's proposal of not having the authorization related
information in the Transmitter Configuration Metadata. The mechanism he has
outlined, which is based on existing standards will work well, I think.

**Comment by mcguinness** [comment]
It seems like there isn't consensus for the proposed change in [draft2](https://openid.github.io/sharedsignals/openid-sharedsignals-framework-1_0.html).  I suggest we revert the change before the draft is published so to set expectations with folks building implementations now of the draft.  We can continue to hash out additional changes on this thread and WG calls to see if we want to include any other proposal before draft2 is published.
